server:
  port: 8080
  shutdown: "graceful"

#datasource
spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/camunda-changelog.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda
    username: admin
    password: admin
  hikari:
    connectionTimeout: 20000
    maximum-pool-size: 100
  logging:
    level:
      "liquibase": info


#camunda
camunda:
  bpm:
    database:
      type: postgres
      schema-update: false
    admin-user:
      id: demo
      password: demo




